module.exports = {
  likes: '{ likes, plural, ' +
          '=0 { no likes }' +
          '=1 { # like }' +
          'other { # likes }}',
  'logout': 'Logout',
  'english': 'English',
  'spanish': 'Spanish',
  'signup.subheading': 'Signup to watch your friends\' pictures studying at Platzi',
  'signup.facebook': 'Signup with Facebook',
  'signup.text': 'Signup',
  'email': 'Email',
  'username': 'Username',
  'fullname': 'Fullname',
  'password': 'Password',
  'signup.call-to-action': 'Signup',
  'signup.have-account': 'Already have an account?',
  'signin': 'Signin',
  'signin.not-have-account': '¿Don\'t have an account?',
  'language': 'Language',
  'upload-picture': 'Upload picture',
  'upload': 'Upload',
  'Páginas': 'Pages',
  'Inicio': 'Home',
  'Proyectos': 'Projects',
  'Acerca de': 'About',
  "Desarrollador de Software":"Software Developer",
  "Hoja de Vida":"Curriculum vitae",
  "Innovador por naturaleza, desarrollador de software de profesión y futbolista de corazón. Apasionado por la tecnología con más de 5 años de experiencia en el desarrollo de software, involucrado en desarrollos web, móviles, y de escritorio.":"Innovative by nature, professional software developer and footballer at heart. Passionate about technology with more than 5 years of experience in software development, involved in web, mobile and desktop development.",
  "Terminos y Condiciones":"Terms and Contitions",
  "Pedro Caicedo - Desarrollador de Software":"Pedro Caicedo - Software Developer",
  "Leer más":"Read more",
  "<b>PCaicedo</b> es una página web que nace de la necesidad de compartir los conocimientos y experiencias en el ambito profesional y cotidiano. El contenido de la página principalmente está enfocado al desarrollo de software, aunque también encontrarás algunos datos y concejos útiles de la cotidianidad. A continuación lo invitamos a que conozca un poco más.":"<b>PCaicedo</b> is a web page that arises from the need to share knowledge and experiences in the professional and daily environment. The content of the page is mainly focused on software development, although you will also find some useful information and tips for everyday life. Then we invite you to know a little more.",
  "Reseña":"Review",
  "Innovador por naturaleza, desarrollador de software de profesión y futbolista de corazón. Apasionado por la tecnología con más de 5 años de experiencia en el desarrollo de software, involucrado en desarrollos web, móviles, y de escritorio. Formado en la <a href=\"http://campusvirtual.ucv.ve/\" target=\"_black\">UCV</a> y miembro del grupo de desarrollo <a href=\"https://cuado.co\" target=\"_black\">Cuado</a>. En aprendizaje constante desde internet (<a href=\"https://platzi.com/r/caicedo1089/\" target=\"_black\">Platzi</a>), buscando nuevas oportunidades de crecimiento profesional y personal.":"Innovative by nature, professional software developer and footballer at heart. Passionate about technology with more than 5 years of experience in software development, involved in web, mobile, and desktop developments. Formed in the <a href=\"http://campusvirtual.ucv.ve/\" target=\"_black\"> UCV </a> and member of the development group <a href = \"https://cuado.co\"target = \"_black\"> Cuado </a>. In constant learning from the internet (<a href=\"https://platzi.com/r/caicedo1089/\" target=\"_black\"> Platzi </a>), looking for new opportunities for professional and personal growth.",
  "Intereses":"Interests",
  "Desde mi niñez las ciencias me han interesado, el saber como funcionan los objetos o sistemas, conocer el por qué de su funcionamiento; eran preguntas muy usuales que no he dejado de hacer desde entonces. Al encender mi primera computadora surgieron muchas preguntas que he tratado de responder con la ayuda de la academia, grupos de desarrollo e internet. Todas las áreas donde se ve involucrado un sistema de cómputo son interesantes, pero en la actualidad estoy enfocado en el desarrollo web y móvil.":"From my childhood the sciences have interested me, to know how objects or systems work, to know the why of their functioning; They were very usual questions that I have not stopped doing since then. When I turned on my first computer, many questions came up that I tried to answer with the help of academia, development groups and the internet. All areas where a computer system is involved are interesting, but I am currently focused on web and mobile development.",
  "¿Deseas contactarme?":"Do you want to contact me?",
  "Puedes escribirme directamente al <a href=\"mailto:info@pcaicedo.com\">info@pcaicedo.com</a> o a través de mis redes sociales.":"You can write me directly at <a href=\"mailto:info@pcaicedo.com\"> info@pcaicedo.com </a> or through my social networks.",
  "Computación Gráfica":"Computer graphics",
  "Investigación":"Investigation",
  "desarrollo":"development",
  "Error 404 - Página no encontrada":"Error 404 - Page not found",
  "Disculpe pero esa página no está en nuestros servidores :'(":"Sorry but that page is not in our servers :'("
}
